# Generated by Django 4.2.7 on 2023-11-29 04:51

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                ("rank", models.IntegerField()),
                ("title", models.CharField(max_length=50)),
                ("director", models.CharField(max_length=10)),
                ("actor1", models.CharField(max_length=10)),
                ("actor2", models.CharField(max_length=10)),
                ("date", models.DateField()),
                ("audience", models.IntegerField()),
                ("genre", models.CharField(max_length=20)),
                ("award", models.CharField(max_length=20)),
            ],
        ),
    ]
