# Generated by Django 4.2.7 on 2023-11-29 04:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="date",
            field=models.CharField(max_length=20),
        ),
    ]
