# Generated by Django 4.2.7 on 2023-11-29 05:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0002_alter_movie_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="movie",
            old_name="actor1",
            new_name="감독",
        ),
        migrations.RenameField(
            model_name="movie",
            old_name="award",
            new_name="개봉일",
        ),
        migrations.RenameField(
            model_name="movie",
            old_name="audience",
            new_name="관객수",
        ),
        migrations.RenameField(
            model_name="movie",
            old_name="date",
            new_name="수상",
        ),
        migrations.RenameField(
            model_name="movie",
            old_name="rank",
            new_name="순위",
        ),
        migrations.RenameField(
            model_name="movie",
            old_name="year",
            new_name="연도",
        ),
        migrations.RenameField(
            model_name="movie",
            old_name="genre",
            new_name="장르",
        ),
        migrations.RenameField(
            model_name="movie",
            old_name="title",
            new_name="제목",
        ),
        migrations.RenameField(
            model_name="movie",
            old_name="actor2",
            new_name="주연1",
        ),
        migrations.RenameField(
            model_name="movie",
            old_name="director",
            new_name="주연2",
        ),
    ]
