# Generated by Django 4.2.7 on 2023-11-29 05:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0003_rename_actor1_movie_감독_rename_award_movie_개봉일_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="관객수",
            field=models.IntegerField(null=True),
        ),
    ]
