# Generated by Django 4.2.7 on 2023-11-29 06:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0005_alter_movie_관객수"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="관객수",
            field=models.IntegerField(null=True),
        ),
    ]
